import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import FeatureGrid from "@/components/FeatureGrid";
import PricingCards from "@/components/PricingCards";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Navbar />
      <Hero />
      
      <FeatureGrid />
      <PricingCards />
      
      <section className="px-6 py-16 dark:bg-gray-950">
        <div className="mx-auto max-w-6xl">
          <div className="mb-10 text-center">
            <h2 className="text-4xl font-black text-gray-950 dark:text-white">See it in Action</h2>
            <p className="mt-3 text-gray-600 dark:text-gray-400">Real plans generated by PlanWise AI</p>
          </div>
          
          <div className="grid gap-6 lg:grid-cols-3">
            {/* Q4 Expansion Strategy */}
            <div className="rounded-2xl border border-indigo-100 dark:border-gray-700 bg-white dark:bg-gray-800 p-6 card-shadow">
              <div className="mb-4 flex items-start justify-between">
                <div>
                  <p className="text-sm font-semibold text-gray-600 dark:text-gray-400">Generated 3m ago by PlanWise AI</p>
                  <h3 className="mt-2 text-lg font-bold text-gray-950 dark:text-white">Q4 Expansion Strategy</h3>
                </div>
                <span className="rounded-full bg-emerald-100 dark:bg-emerald-900/30 px-3 py-1 text-xs font-bold text-emerald-700 dark:text-emerald-400">ACTIVE</span>
              </div>
              
              <div className="mt-6 rounded-2xl bg-indigo-50 dark:bg-indigo-900/20 p-4">
                <p className="text-xs text-gray-600 dark:text-gray-400">COMPLEXITY SCORE</p>
                <div className="mt-2 flex items-baseline gap-2">
                  <span className="text-2xl font-black text-indigo-600 dark:text-indigo-400">84</span>
                  <span className="text-gray-600 dark:text-gray-400">/100</span>
                </div>
                <div className="mt-3 h-2 w-full rounded-full bg-gray-200 dark:bg-gray-700">
                  <div className="h-full w-[84%] rounded-full bg-indigo-600"></div>
                </div>
                <p className="mt-2 text-xs text-gray-600 dark:text-gray-400">This plan requires high cross-departmental coordination. 3 risks identified.</p>
              </div>
            </div>
            
            {/* Market Saturation Analysis */}
            <div className="rounded-2xl border border-indigo-100 dark:border-gray-700 bg-white dark:bg-gray-800 p-6 card-shadow">
              <div className="mb-4">
                <p className="text-xs font-semibold text-gray-600 dark:text-gray-400">Market Research Task</p>
                <h3 className="mt-2 text-lg font-bold text-gray-950 dark:text-white">Market Saturation Analysis</h3>
              </div>
              
              <div className="mt-6 space-y-3">
                <div className="flex items-center gap-3 rounded-lg border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-900/20 p-3">
                  <span className="text-lg">📊</span>
                  <div className="flex-1">
                    <p className="text-xs font-bold text-yellow-900 dark:text-yellow-400">HIGH PRIORITY</p>
                    <p className="text-xs text-yellow-800 dark:text-yellow-300">AI identified 3 potential entry points in APAC regions based on current trend data.</p>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Operational Risk Assessment */}
            <div className="rounded-2xl border border-indigo-100 dark:border-gray-700 bg-white dark:bg-gray-800 p-6 card-shadow">
              <div className="mb-4">
                <p className="text-xs font-semibold text-gray-600 dark:text-gray-400">Operations Task</p>
                <h3 className="mt-2 text-lg font-bold text-gray-950 dark:text-white">Operational Risk Assessment</h3>
              </div>
              
              <div className="mt-6 space-y-3">
                <div className="flex items-start gap-3 rounded-lg border border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/20 p-3">
                  <span className="text-lg">⚠️</span>
                  <div className="flex-1">
                    <p className="text-xs font-bold text-red-900 dark:text-red-400">CRITICAL BOTTLENECK</p>
                    <p className="text-xs text-red-800 dark:text-red-300">Resource Conflict: UI/UX Team over capacity for Sprint 12</p>
                    <button className="mt-2 text-xs font-semibold text-red-700 dark:text-red-400 hover:underline">Auto-reschedule ›</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <section className="px-6 py-16 dark:bg-gray-950 text-center">
        <div className="mx-auto max-w-2xl rounded-[2rem] bg-indigo-50 dark:bg-gray-800 p-8 md:p-12">
          <h2 className="text-3xl font-black text-gray-950 dark:text-white">Ready to Simplify?</h2>
          <p className="mt-4 text-gray-600 dark:text-gray-400">Join 15,000+ project managers turning chaos into clarity every single day.</p>
          <button className="mt-6 rounded-2xl bg-indigo-600 px-8 py-3 font-bold text-white hover:bg-indigo-700">
            Get Started Free
          </button>
        </div>
      </section>

      <Footer />
    </>
  );
}
